tap "anomalyco/tap", trusted: true
tap "colindean/fonts-nonfree", trusted: true
tap "ublue-os/experimental-tap", trusted: true
tap "ublue-os/tap", trusted: true
cask "jetbrains-toolbox-linux"
cask "visual-studio-code-linux"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-azuretools.vscode-containers"
brew "atuin"
brew "bat"
brew "chezmoi"
brew "devcontainer"
brew "eza"
brew "fzf"
brew "gh"
brew "herdr"
brew "llama.cpp"
brew "mise"
brew "neovim"
brew "pi-coding-agent"
brew "podman-tui"
brew "ripgrep"
brew "starship"
brew "tealdeer"
brew "tmux"
brew "trash-cli"
brew "yq"
brew "zoxide"
brew "anomalyco/tap/opencode", trusted: true
cask "font-0xproto-nerd-font"
cask "font-arial"
cask "font-arial-black"
cask "font-blex-mono-nerd-font"
cask "font-caskaydia-mono-nerd-font"
cask "font-comic-sans-ms"
cask "font-comic-shanns-mono-nerd-font"
cask "font-dejavu"
cask "font-droid-sans-mono-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-fira-sans"
cask "font-go-mono-nerd-font"
cask "font-impact"
cask "font-jetbrains-mono-nerd-font"
cask "colindean/fonts-nonfree/font-microsoft-aptos", trusted: true
cask "colindean/fonts-nonfree/font-microsoft-fluent", trusted: true
cask "colindean/fonts-nonfree/font-microsoft-office", trusted: true
cask "font-montserrat"
cask "font-noto-sans"
cask "font-roboto"
cask "font-sauce-code-pro-nerd-font"
cask "font-source-code-pro"
cask "font-ubuntu"
cask "font-ubuntu-nerd-font"
cask "ublue-os/tap/goose-linux", trusted: true
cask "ublue-os/tap/lm-studio-linux", trusted: true
flatpak "com.discordapp.Discord"
flatpak "com.github.PintaProject.Pinta"
flatpak "com.github.marhkb.Pods"
flatpak "com.github.rafostar.Clapper"
flatpak "com.github.tchx84.Flatseal"
flatpak "com.google.Chrome"
flatpak "com.mattjakeman.ExtensionManager"
flatpak "com.ranfdev.DistroShelf"
flatpak "com.spotify.Client"
flatpak "com.super_productivity.SuperProductivity"
flatpak "com.ticktick.TickTick"
flatpak "io.github.flattool.Ignition"
flatpak "io.github.flattool.Warehouse"
flatpak "io.github.kolunmi.Bazaar"
flatpak "io.gitlab.adhami3310.Impression"
flatpak "io.missioncenter.MissionCenter"
flatpak "io.podman_desktop.PodmanDesktop"
flatpak "io.speedofsound.SpeedOfSound"
flatpak "org.gnome.Calculator"
flatpak "org.gnome.Calendar"
flatpak "org.gnome.Characters"
flatpak "org.gnome.Connections"
flatpak "org.gnome.Contacts"
flatpak "org.gnome.DejaDup"
flatpak "org.gnome.FileRoller"
flatpak "org.gnome.Firmware"
flatpak "org.gnome.Logs"
flatpak "org.gnome.Loupe"
flatpak "org.gnome.Maps"
flatpak "org.gnome.NautilusPreviewer"
flatpak "org.gnome.Papers"
flatpak "org.gnome.SimpleScan"
flatpak "org.gnome.TextEditor"
flatpak "org.gnome.Weather"
flatpak "org.gnome.baobab"
flatpak "org.gnome.clocks"
flatpak "org.gnome.font-viewer"
flatpak "org.mozilla.firefox"
flatpak "org.mozilla.thunderbird_esr"
flatpak "page.tesk.Refine"
